Semantic Changes
nhcarrigan/nhcarrigan pull request #2
Opened 2020-12-15 09:38 UTC by dumbcoder7

# Pull Request

## Description:

Cleared some textual inaccuracies and tried to beautify the placement of GitHub cards on the page. Also tried to align the table. Should I design it using CSS? We can add colours if we do that.

## Related Issue:

Closes #1

2020-12-15 15:42 UTC, nhcarrigan requested changes
Thank you for your efforts here! I've left a couple of suggested tweaks in the comments below. 🙂 

Applying colours to the table would be cool, but I'd want to be sure that it would not interfere with GitHub's new dark mode (so colours should remain within AA contrast standard regardless of which theme a user chooses).

2020-12-15 15:42 UTC, nhcarrigan commented on README.md
> +I began my developer journey in April of 2020, starting at the very top of the [freeCodeCamp](https://freecodecamp.org/) curriculum. I picked up the knowledge of HTML, CSS, JavaScript, node.js, React
```suggestion
I began my developer journey in April of 2020, starting at the very top of the [freeCodeCamp](https://freecodecamp.org/) curriculum. I picked up my knowledge of HTML, CSS, JavaScript, node.js, React, and D3. Some of those tools stuck, while others did not. After completing the Full Stack web development certification, I started exploring TypeScript and fell in love with it. I used it first for a couple of small projects, then ended up building a Discord bot with it. When freeCodeCamp rolled out the Python curriculum I started exploring Python - but I ended up tabling those studies until later on. I recently picked up Angular and began exploring it, and so far am greatly enjoying what it has to offer!
```
Small nitpick, but reads a bit smoother IMO.

2020-12-15 15:42 UTC, nhcarrigan commented on README.md
> +</p>
```suggestion
<p align = "center">
  <img src = "https://github-readme-stats.vercel.app/api?username=nhcarrigan&count_private=true&show_icons=true&theme=synthwave" width="50%" alt="Statistics"/>
  <img src ="https://github-readme-stats.vercel.app/api/top-langs/?username=nhcarrigan&show_icons=true&theme=synthwave" alt = "Top Languages Cards" width="50%" />  
</p>

```
A couple of things here:

- Let's remove the commented out portions.
- Remove the `br` tag. This renders to the page and `br` tags are detrimental to accessibility.
- Shrink the top image to be the same size as the bottom image.

2020-12-16 13:03 UTC, dumbcoder7 commented on README.md
> +</p>
Oh my, sorry I left the comments in there. 
But I really like the view of the Stats card being larger than the language cards. Have you previewed it? If you have and still don't like it, I will surely make the changes. Let me add both screenshots here.

When width is equal:
![image](https://user-images.githubusercontent.com/43912470/102351144-fcf8b200-3fcb-11eb-92a2-3311968ac9bf.png)

When width is as specified by my commit:
![image](https://user-images.githubusercontent.com/43912470/102351710-e737bc80-3fcc-11eb-9f0c-c52923917da8.png)

2020-12-16 13:04 UTC, dumbcoder7 commented on README.md
>  ![Social Media Banner](./banner.png)
Should I also center this banner @nhcarrigan  ?

2020-12-16 16:12 UTC, nhcarrigan commented on README.md
> +</p>
I did preview it locally, yes - and I'm of the opinion that they look a bit cleaner when they're the same size. It makes them feel more unified, instead of just cobbled together.

2020-12-16 16:13 UTC, nhcarrigan commented on README.md
>  ![Social Media Banner](./banner.png)
That's a good idea, I think 🙂

2020-12-16 20:43 UTC, dumbcoder7 commented on README.md
> +</p>
Committed.

2020-12-16 21:18 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

2020-12-16 21:18 UTC, merged